name: Test and publish crates

on:
  push:
  pull_request:

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cargo test
        run: cargo test

      - name: Publish test
        run: |
          cargo publish -p ts-bind-macros --dry-run
          cargo publish -p ts-bind --dry-run

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true

      - name: Publish ts-bind-macros
        run: cargo publish -p ts-bind-macros

      - name: Publish ts-bind
        run: cargo publish -p ts-bind
